# SwiftLint configuration for swift-iso-8601
# Inherits from the shared parent configuration in swift-standards

parent_config: https://raw.githubusercontent.com/swift-standards/swift-standards/main/.swiftlint.yml

# Package-specific overrides
disabled_rules:
  - function_parameter_count  # DateTime initializers need many parameters
  - force_try  # Internal initializers with validated inputs use force try
  - cyclomatic_complexity  # Complex parsing logic for ISO 8601 formats
  - opening_brace  # Conflicts with swift-format line length rules
